version: '2'

services:
  paradb-web:
    image: paradb/paradb:localhost
    container_name: "paradb-web"
    stdin_open: true
    restart: always
    ports:
      - "80:80"
      - "6000:6000"
    networks:
      - paradb-local
      
  bioportainer-blast:
    image: wurmlab/sequenceserver
    container_name: "paradb-blast"
    stdin_open: true
    restart: always
    ports:
      - "4567:4567"
    networks:
      - paradb-local
    volumes:
      - ${PWD}/paradb_blast:/db
      
  paradb-watchtower:
    image: v2tec/watchtower
    stdin_open: true
    restart: always
    container_name: "bioportainer-watchtower"
    command: --cleanup paradb-web paradb-watchtower paradb-blast
    networks:
      - paradb-local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  paradb-local:
    driver: bridge

volumes:
   paradb_blast:
